"""
Django settings for Play project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(2q57)lckc#3s1agkln0iz$5a2aiv+2%9^sqwj0(d5yfm=se75'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Play.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'mainapp-ui/build'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Play.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
PASSWORD = 'Kobalter97'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = (
    (BASE_DIR / 'mainapp-ui/build/static'),
)


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'artistsin20@gmail.com'
EMAIL_HOST_PASSWORD = PASSWORD
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

'''
EMAIL_HOST = 'msk01-exch13.gazprom-neft.local'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'lkzgpnito.info@gazprom-neft.ru'
EMAIL_HOST_PASSWORD = 'A55SvdGjgMc7RcUY87hjcn'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
'''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

#DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Константы для быстрого заполнения
VENDOR = 'Vendor name' # Имя компании разработчика (напр. 'GPN ITO')
PRODUCT = 'Product name' # Имя продукта, компонента, сервиса (напр. 'lkz.002')
VERSION = 'Device version' # Номер версии в формате SemVer2.0.0 (напр. '1.0.0')
CEF = '0' # Формат сообщения и версия (по умолчанию 0)


LOGGING = {
    'version': 1,
    'disable_existing_logging': False,
    'formatters': {
        # Форматтер для arcsight, описание формата передачи данных для CEF
        'arcsight': {
            'format': '%(day)s host CEF:' + CEF + '|' + VENDOR + '|' + PRODUCT + '|' + VERSION + '|%(funcName)s|%(message)s|%(levelno)s|src=%(src)s dst=%(dst)s shost=%(shost)s suid=%(suid)s suser=%(suser)s msg=%(dmsg)s end=%(end)s',
        },
    },
    'handlers': {
        # Хэндлер для записи логгера в консоль
        'arcsight_console': {
            'level': 'DEBUG', # Для записи процесса любого уровня
            'class': 'logging.StreamHandler',
            'formatter': 'arcsight',
        },
        # Хэндлер для записи логгера в файл
        'arcsight_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'arcsight',
            'filename': './arcsight.log', # Местонахождение/наименование файла для записи лога
        },
    },
    'loggers': {
        'arcsight': {
            'level': 'DEBUG',
            'handlers': ['arcsight_console', 'arcsight_file'], # Направления записи лога
        },
    },
}











